package cn.com.taiji.pojo;

public class Class {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.id
     *
     * @mbg.generated Wed Mar 13 13:58:36 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.classname
     *
     * @mbg.generated Wed Mar 13 13:58:36 CST 2019
     */
    private String classname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.classroom
     *
     * @mbg.generated Wed Mar 13 13:58:36 CST 2019
     */
    private String classroom;

    public Class() {
    }

    public Class(Integer id, String classname, String classroom) {
        this.id = id;
        this.classname = classname;
        this.classroom = classroom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.id
     *
     * @return the value of class.id
     *
     * @mbg.generated Wed Mar 13 13:58:36 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.id
     *
     * @param id the value for class.id
     *
     * @mbg.generated Wed Mar 13 13:58:36 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.classname
     *
     * @return the value of class.classname
     *
     * @mbg.generated Wed Mar 13 13:58:36 CST 2019
     */
    public String getClassname() {
        return classname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.classname
     *
     * @param classname the value for class.classname
     *
     * @mbg.generated Wed Mar 13 13:58:36 CST 2019
     */
    public void setClassname(String classname) {
        this.classname = classname == null ? null : classname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.classroom
     *
     * @return the value of class.classroom
     *
     * @mbg.generated Wed Mar 13 13:58:36 CST 2019
     */
    public String getClassroom() {
        return classroom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.classroom
     *
     * @param classroom the value for class.classroom
     *
     * @mbg.generated Wed Mar 13 13:58:36 CST 2019
     */
    public void setClassroom(String classroom) {
        this.classroom = classroom == null ? null : classroom.trim();
    }

    @Override
    public String toString() {
        return "Class{" +
                "id=" + id +
                ", classname='" + classname + '\'' +
                ", classroom='" + classroom + '\'' +
                '}';
    }
}